# Generated by Django 6.0.6 on 2026-06-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=255)),
                ('termin', models.DateField()),
                ('status', models.CharField(choices=[('Nowe', 'Nowe'), ('W trakcie', 'W trakcie'), ('Zakończone', 'Zakończone')], default='Nowe', max_length=20)),
            ],
        ),
    ]
